//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapRef) DeepCopyInto(out *ConfigMapRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapRef.
func (in *ConfigMapRef) DeepCopy() *ConfigMapRef {
	if in == nil {
		return nil
	}
	out := new(ConfigMapRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialStruct) DeepCopyInto(out *CredentialStruct) {
	*out = *in
	out.S3Auth = in.S3Auth
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialStruct.
func (in *CredentialStruct) DeepCopy() *CredentialStruct {
	if in == nil {
		return nil
	}
	out := new(CredentialStruct)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DLTDeployment) DeepCopyInto(out *DLTDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DLTDeployment.
func (in *DLTDeployment) DeepCopy() *DLTDeployment {
	if in == nil {
		return nil
	}
	out := new(DLTDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DLTDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DLTDeploymentList) DeepCopyInto(out *DLTDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DLTDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DLTDeploymentList.
func (in *DLTDeploymentList) DeepCopy() *DLTDeploymentList {
	if in == nil {
		return nil
	}
	out := new(DLTDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DLTDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DLTDeploymentSpec) DeepCopyInto(out *DLTDeploymentSpec) {
	*out = *in
	out.Credential = in.Credential
	if in.Jobs != nil {
		in, out := &in.Jobs, &out.Jobs
		*out = make([]Job, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DLTDeploymentSpec.
func (in *DLTDeploymentSpec) DeepCopy() *DLTDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(DLTDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DLTDeploymentStatus) DeepCopyInto(out *DLTDeploymentStatus) {
	*out = *in
	if in.CreatedJobs != nil {
		in, out := &in.CreatedJobs, &out.CreatedJobs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DLTDeploymentStatus.
func (in *DLTDeploymentStatus) DeepCopy() *DLTDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(DLTDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSourceStruct) DeepCopyInto(out *DataSourceStruct) {
	*out = *in
	in.Keys.DeepCopyInto(&out.Keys)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceStruct.
func (in *DataSourceStruct) DeepCopy() *DataSourceStruct {
	if in == nil {
		return nil
	}
	out := new(DataSourceStruct)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Job) DeepCopyInto(out *Job) {
	*out = *in
	in.WorkerContainer.DeepCopyInto(&out.WorkerContainer)
	in.DataSource.DeepCopyInto(&out.DataSource)
	if in.Workers != nil {
		in, out := &in.Workers, &out.Workers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Job.
func (in *Job) DeepCopy() *Job {
	if in == nil {
		return nil
	}
	out := new(Job)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobDatasetKeysStruct) DeepCopyInto(out *JobDatasetKeysStruct) {
	*out = *in
	if in.Train != nil {
		in, out := &in.Train, &out.Train
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Validation != nil {
		in, out := &in.Validation, &out.Validation
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Test != nil {
		in, out := &in.Test, &out.Test
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobDatasetKeysStruct.
func (in *JobDatasetKeysStruct) DeepCopy() *JobDatasetKeysStruct {
	if in == nil {
		return nil
	}
	out := new(JobDatasetKeysStruct)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3AuthStruct) DeepCopyInto(out *S3AuthStruct) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3AuthStruct.
func (in *S3AuthStruct) DeepCopy() *S3AuthStruct {
	if in == nil {
		return nil
	}
	out := new(S3AuthStruct)
	in.DeepCopyInto(out)
	return out
}
