# permissions for end users to view dltdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dltdeployment-viewer-role
rules:
- apiGroups:
  - docgroup.com
  resources:
  - dltdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - docgroup.com
  resources:
  - dltdeployments/status
  verbs:
  - get
