---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - docgroup.com
  resources:
  - dltdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - docgroup.com
  resources:
  - dltdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - docgroup.com
  resources:
  - dltdeployments/status
  verbs:
  - get
  - patch
  - update
