apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: all-access
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: all-access-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: all-access
  apiGroup: rbac.authorization.k8s.io

