apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local-data
  namespace: monitoring
  labels:
    type: local
    app: prometheus-deployment
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/local/promdata"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-local-data
  namespace: monitoring
  labels:
    app: prometheus-deployment
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
