apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: zhuangweikang/cndlsys-dev:frontend
        command: ["python3"]
        args: ["FrontEnd.py"]
        imagePullPolicy: Always
        ports:
        - name: listen-port
          containerPort: 5000
        stdin: true
        tty: true
        volumeMounts:
        - name: configuration
          mountPath: /configs
      volumes:
        - name: configuration
          configMap:
            name: cndlsys-config