apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  MONGO_ROOT_USERNAME: YWRtaW4K
  MONGO_ROOT_PASSWORD: cGFzc3dvcmQK
  MONGO_USERNAME: dGVzdAo=
  MONGO_PASSWORD: cGFzc3dvcmQK
  MONGO_USERS_LIST: dGVzdDpkYkFkbWluLHJlYWRXcml0ZTpwYXNzd29yZAo=


# MONGO_ROOT_USERNAME: root
# MONGO_ROOT_PASSWORD: password
# MONGO_USERNAME: test
# MONGO_PASSWORD: password
# MONGO_USERS_LIST: test:dbAdmin,readWrite:password