kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nfs-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/nfs
mountOptions:
- vers=4.1
allowVolumeExpansion: true