# @package _global_
data:
  num_workers: 8
  augmentation:
    spec_augment: True
trainer:
  max_epochs: 16
  accelerator: 'auto'
  devices: 1
  precision: 16
  gradient_clip_val: 400  # Norm cutoff to prevent explosion of gradients
  strategy: ddp
  enable_checkpointing: True
checkpoint:
  save_top_k: 1
  monitor: "wer"
  verbose: True